# Generated by Django 3.2.25 on 2024-04-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replay',
            options={},
        ),
    ]
